version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "phanect"
    groups:
      security:
        applies-to: "security-updates"
        update-types:
          - "minor"
          - "patch"
      security-breaking:
        applies-to: "security-updates"
        update-types:
          - "major"
      compatible:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
      less-prioritized:
        applies-to: "version-updates"
        patterns:
          - "eslint"
          - "eslint-plugin-*"
          - "eslint-config-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "phanect"
