version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: [ "phanect" ]
    open-pull-requests-limit: 0 # only receive security updates

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: [ "phanect" ]
